name: "WechatAgents_go"
version: "1.0.0"
#域名
sercive_hose: "aiagents-wechatagents.hf.space"
#机器人的安全码
security_code: ""
#机器人的wxid
BotWxid: "wxid_tj1hdj6zuh3b12"
database:
  host: ""
  port:
  user: ""
  password: ""

#可用群
chatroom:
  - "39139856094@chatroom"

#防撤回
revokeChatroom:
  - "39139856094@chatroom"