knownGroup:
- chatroom_id: 51809312273@chatroom
  chatroom_name: 阿呆 - 1群
- chatroom_id: 39139856094@chatroom
  chatroom_name: 爱在西元前
- chatroom_id: 15725934943@chatroom
  chatroom_name: IT职场进阶讨论组
- chatroom_id: 38685134707@chatroom
  chatroom_name: "心动预报\U0001F493(摸鱼吃瓜)"
- chatroom_id: 20912594685@chatroom
  chatroom_name: "\U0001F951张小扣的朋友圈\U0001F353"
- chatroom_id: 20989460236@chatroom
  chatroom_name: 花园宝宝成长乐园
- chatroom_id: 21099660658@chatroom
  chatroom_name: "心动预报\U0001F493(备用吃瓜群)"
- chatroom_id: 43232685451@chatroom
  chatroom_name: 文明驾驶安全出行
- chatroom_id: 38807883823@chatroom
  chatroom_name: XYBot交流群-一
- chatroom_id: 14395919264@chatroom
  chatroom_name: TCG憨憨团（TopChampGrp）
